In [1]:
%pip install psycopg2

Requirement already satisfied: psycopg2 in c:\Users\dfang\anaconda3\Lib\site-packages (2.9.11)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import requests
import xml.etree.ElementTree as ET
import pandas as pd
import time

In [4]:
import psycopg2
from sqlalchemy import create_engine, text

In [5]:
data = pd.read_csv('C:/Users/dfang/Downloads/bgg_processed.csv')
data.columns = [col.strip().replace(' ', '_').lower() for col in data.columns]

engine = create_engine("postgresql+psycopg2://postgres:ID#216647dhf@localhost:5432/games")
data = data.to_sql('games', engine, if_exists = 'replace')
print(data)

1000

In [6]:
#Inputs:
complexity = 3
players = 4
min_age = 12
mechanics = ['Hand Management', 'Income', 'Market']

In [7]:
query = text("SELECT * FROM games WHERE complexity_average > :com AND min_age > :age AND (:players BETWEEN min_players AND max_players) AND string_to_array(mechanics,', ') @> CAST(:mech_list AS TEXT[])")
data_filtered = pd.read_sql(query, con=engine, params = {'com': complexity, 'age': min_age, 'players': players, 'mech_list': mechanics})
data_filtered

,index,id,name,year_published,min_players,max_players,play_time,min_age,users_rated,rating_average,bgg_rank,complexity_average,owned_users,mechanics,domains
0,2,224517.0,Brass: Birmingham,2018.0,2,4,120,14,19217,8.66,3,3.91,28785.0,"Hand Management, Income, Loans, Market, Networ...",Strategy Games

In [8]:
query = text("SELECT * FROM games")
data_filtered = pd.read_sql(query, con=engine, params = {'com': complexity, 'age': min_age, 'players': players, 'mech_list': mechanics})
data_filtered

,index,id,name,year_published,min_players,max_players,play_time,min_age,users_rated,rating_average,bgg_rank,complexity_average,owned_users,mechanics,domains
0,0,174430.0,Gloomhaven,2017.0,1,4,120,14,42055,8.79,1,3.86,68323.0,"Action Queue, Action Retrieval, Campaign / Bat...","Strategy Games, Thematic Games"
1,1,161936.0,Pandemic Legacy: Season 1,2015.0,2,4,60,13,41643,8.61,2,2.84,65294.0,"Action Points, Cooperative Game, Hand Manageme...","Strategy Games, Thematic Games"
2,2,224517.0,Brass: Birmingham,2018.0,2,4,120,14,19217,8.66,3,3.91,28785.0,"Hand Management, Income, Loans, Market, Networ...",Strategy Games
3,3,167791.0,Terraforming Mars,2016.0,1,5,120,12,64864,8.43,4,3.24,87099.0,"Card Drafting, Drafting, End Game Bonuses, Han...",Strategy Games
4,4,233078.0,Twilight Imperium: Fourth Edition,2017.0,3,6,480,14,13468,8.70,5,4.22,16831.0,"Action Drafting, Area Majority / Influence, Ar...","Strategy Games, Thematic Games"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,10889.0,Akron,2002.0,2,2,30,7,49,7.10,10343,3.80,40.0,"Pattern Building, Point to Point Movement",Abstract Games
9996,9996,228550.0,Blueshift,2017.0,2,6,130,13,55,7.41,10344,2.67,171.0,"Dice Rolling, Hexagon Grid, Modular Board, Var...",None
9997,9997,71569.0,Kuni Tori!,2010.0,2,6,45,12,58,6.89,10345,2.29,82.0,"Card Drafting, Deck Bag and Pool Building, Han...",None
9998,9998,16793.0,Second World War at Sea: Leyte Gulf,2005.0,2,2,120,12,54,7.05,10346,3.42,243.0,"Hexagon Grid, Minimap Resolution, Paper-and-Pe...",Wargames
9999,9999,121995.0,Blurble,2013.0,2,12,30,6,126,6.26,10347,1.25,332.0,Pattern Recognition,None

In [ ]:
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS games_base"))
    conn.execute(text("DROP TABLE IF EXISTS games_mechanics"))
    conn.execute(text("DROP TABLE IF EXISTS mechanics"))

    conn.execute(text("""
        CREATE TABLE games_base AS 
        SELECT id, name, complexity_average, min_age, min_players, max_players, rating_average, bgg_rank, owned_users
        FROM games;
    """))
    
    conn.execute(text("""
        CREATE TABLE game_mechanics AS
        SELECT 
            id AS game_id, 
            trim(unnest(string_to_array(mechanics, ','))) AS mechanic_name
        FROM games;
    """))

    conn.execute(text("""CREATE TABLE mechanics AS 
        SELECT DISTINCT mechanic_name 
        FROM game_mechanics_map;"""))
    
    conn.commit()

In [12]:
query = text("SELECT g.*, m.mechanic_name FROM games_base g JOIN game_mechanics m ON g.id = m.game_id WHERE m.mechanic_name = 'Hand Management';")
data_filtered_1 = pd.read_sql(query, con=engine)
data_filtered_1

,id,name,complexity_average,min_age,min_players,max_players,rating_average,bgg_rank,owned_users,mechanic_name
0,174430.0,Gloomhaven,3.86,14,1,4,8.79,1,68323.0,Hand Management
1,161936.0,Pandemic Legacy: Season 1,2.84,13,2,4,8.61,2,65294.0,Hand Management
2,224517.0,Brass: Birmingham,3.91,14,2,4,8.66,3,28785.0,Hand Management
3,167791.0,Terraforming Mars,3.24,12,1,5,8.43,4,87099.0,Hand Management
4,291457.0,Gloomhaven: Jaws of the Lion,3.55,14,1,4,8.87,6,21609.0,Hand Management
...,...,...,...,...,...,...,...,...,...,...
2558,31971.0,Burgoo,1.23,10,2,5,5.69,10305,1889.0,Hand Management
2559,278989.0,Kung Fu,2.00,6,2,5,7.21,10309,89.0,Hand Management
2560,10890.0,Behind,2.67,10,2,2,6.94,10321,128.0,Hand Management
2561,306697.0,Smash Up: Marvel,0.00,12,2,4,8.18,10326,252.0,Hand Management
2562,71569.0,Kuni Tori!,2.29,12,2,6,6.89,10345,82.0,Hand Management