In [1]:
%pip install psycopg2

Requirement already satisfied: psycopg2 in c:\Users\dfang\anaconda3\Lib\site-packages (2.9.11)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import requests
import xml.etree.ElementTree as ET
import pandas as pd
import time

In [3]:
import psycopg2
from sqlalchemy import create_engine, text

In [4]:
data = pd.read_csv('C:/Users/dfang/Downloads/bgg_processed (1).csv')
data.columns = [col.strip().replace(' ', '_').lower() for col in data.columns]

engine = create_engine("postgresql+psycopg2://postgres:ID#216647dhf@localhost:5432/games")
data = data.to_sql('games', engine, if_exists = 'replace')
print(data)

709

In [5]:
#Inputs:
complexity = 3
players = 4
min_age = 12
mechanics = ['Hand Management', 'Income', 'Market']

In [6]:
query = text("SELECT * FROM games WHERE complexity_average > :com AND min_age > :age AND (:players BETWEEN min_players AND max_players) AND string_to_array(mechanics,', ') @> CAST(:mech_list AS TEXT[])")
data_filtered = pd.read_sql(query, con=engine, params = {'com': complexity, 'age': min_age, 'players': players, 'mech_list': mechanics})
data_filtered

,index,id,name,year_published,min_players,max_players,play_time,min_age,users_rated,rating_average,bgg_rank,complexity_average,owned_users,mechanics,domains
0,2,224517.0,Brass: Birmingham,2018.0,2,4,120,14,19217,8.66,3,3.91,28785.0,"Hand Management, Income, Loans, Market, Networ...",Strategy Games

In [7]:
query = text("SELECT * FROM games")
data_filtered = pd.read_sql(query, con=engine, params = {'com': complexity, 'age': min_age, 'players': players, 'mech_list': mechanics})
data_filtered

,index,id,name,year_published,min_players,max_players,play_time,min_age,users_rated,rating_average,bgg_rank,complexity_average,owned_users,mechanics,domains
0,0,174430.0,Gloomhaven,2017.0,1,4,120,14,42055,8.79,1,3.86,68323.0,"Action Queue, Action Retrieval, Campaign / Bat...","Strategy Games, Thematic Games"
1,1,161936.0,Pandemic Legacy: Season 1,2015.0,2,4,60,13,41643,8.61,2,2.84,65294.0,"Action Points, Cooperative Game, Hand Manageme...","Strategy Games, Thematic Games"
2,2,224517.0,Brass: Birmingham,2018.0,2,4,120,14,19217,8.66,3,3.91,28785.0,"Hand Management, Income, Loans, Market, Networ...",Strategy Games
3,3,167791.0,Terraforming Mars,2016.0,1,5,120,12,64864,8.43,4,3.24,87099.0,"Card Drafting, Drafting, End Game Bonuses, Han...",Strategy Games
4,4,233078.0,Twilight Imperium: Fourth Edition,2017.0,3,6,480,14,13468,8.70,5,4.22,16831.0,"Action Drafting, Area Majority / Influence, Ar...","Strategy Games, Thematic Games"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9704,9704,1410.0,Trouble,1965.0,2,4,45,4,3255,3.79,20339,1.05,4962.0,Roll / Spin and Move,Children's Games
9705,9705,7316.0,Bingo,1530.0,2,99,60,5,2154,2.85,20341,1.05,1533.0,"Betting and Bluffing, Bingo, Pattern Recognition",Party Games
9706,9706,5048.0,Candy Land,1949.0,2,4,30,3,4006,3.18,20342,1.08,5788.0,Roll / Spin and Move,Children's Games
9707,9707,5432.0,Chutes and Ladders,-200.0,2,6,30,3,3783,2.86,20343,1.02,4400.0,"Dice Rolling, Grid Movement, Race, Roll / Spin...",Children's Games
9708,9708,11901.0,Tic-Tac-Toe,-1300.0,2,2,1,4,3275,2.68,20344,1.16,1374.0,"Paper-and-Pencil, Pattern Building","Abstract Games, Children's Games"

In [15]:
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS games_base"))
    conn.execute(text("DROP TABLE IF EXISTS game_mechanics"))
    conn.execute(text("DROP TABLE IF EXISTS game_domains"))
    conn.execute(text("DROP TABLE IF EXISTS mechanics"))

    conn.execute(text("""
        CREATE TABLE games_base AS 
        SELECT id, name, complexity_average, min_age, min_players, max_players, rating_average, bgg_rank, owned_users
        FROM games;
    """))
    
    conn.execute(text("""
        CREATE TABLE game_mechanics AS
        SELECT 
            id AS game_id, 
            trim(unnest(string_to_array(mechanics, ','))) AS mechanic_name
        FROM games;
    """))

    conn.execute(text("""
        CREATE TABLE game_domains AS
        SELECT 
            id AS game_id, 
            trim(unnest(string_to_array(domains, ','))) AS domain_name
        FROM games;
"""))

    conn.execute(text("""CREATE TABLE mechanics AS 
        SELECT DISTINCT mechanic_name 
        FROM game_mechanics_map;"""))
    
    conn.commit()

In [20]:
query = text("SELECT g.*, m.mechanic_name, d.domain_name FROM games_base g JOIN game_mechanics m ON g.id = m.game_id JOIN game_domains d ON g.id = d.game_id;")
data_filtered_1 = pd.read_sql(query, con=engine)
data_filtered_1

,id,name,complexity_average,min_age,min_players,max_players,rating_average,bgg_rank,owned_users,mechanic_name,domain_name
0,174430.0,Gloomhaven,3.86,14,1,4,8.79,1,68323.0,Action Queue,Thematic Games
1,174430.0,Gloomhaven,3.86,14,1,4,8.79,1,68323.0,Action Queue,Strategy Games
2,174430.0,Gloomhaven,3.86,14,1,4,8.79,1,68323.0,Action Retrieval,Thematic Games
3,174430.0,Gloomhaven,3.86,14,1,4,8.79,1,68323.0,Action Retrieval,Strategy Games
4,174430.0,Gloomhaven,3.86,14,1,4,8.79,1,68323.0,Campaign / Battle Card Driven,Thematic Games
...,...,...,...,...,...,...,...,...,...,...,...
38083,5432.0,Chutes and Ladders,1.02,3,2,6,2.86,20343,4400.0,Square Grid,Children's Games
38084,11901.0,Tic-Tac-Toe,1.16,4,2,2,2.68,20344,1374.0,Paper-and-Pencil,Children's Games
38085,11901.0,Tic-Tac-Toe,1.16,4,2,2,2.68,20344,1374.0,Paper-and-Pencil,Abstract Games
38086,11901.0,Tic-Tac-Toe,1.16,4,2,2,2.68,20344,1374.0,Pattern Building,Children's Games
38087,11901.0,Tic-Tac-Toe,1.16,4,2,2,2.68,20344,1374.0,Pattern Building,Abstract Games

In [14]:
query = text("SELECT COUNT(DISTINCT mechanic_name) FROM game_mechanics GROUP BY mechanic_name;")
data_filtered_2 = pd.read_sql(query, con=engine)
data_filtered_2

     count
0        1
1        1
2        1
3        1
4        1
..     ...
177      1
178      1
179      1
180      1
181      1

[182 rows x 1 columns]

In [18]:
csv_path = "C:/Users/dfang/Downloads/datafiltered.csv"
data_filtered_1.to_csv(csv_path, index=False, encoding='utf-8')
print(f"Table '{data_filtered_1}' exported successfully to '{csv_path}'")

Table '             id              name  complexity_average  min_age  min_players  \
0           1.0        Die Macher                4.32       14            3
1           1.0        Die Macher                4.32       14            3
2           1.0        Die Macher                4.32       14            3
3           1.0        Die Macher                4.32       14            3
4           1.0        Die Macher                4.32       14            3
...         ...               ...                 ...      ...          ...
38083  322289.0  Darwin's Journey                3.74       14            1
38084  322289.0  Darwin's Journey                3.74       14            1
38085  322289.0  Darwin's Journey                3.74       14            1
38086  322289.0  Darwin's Journey                3.74       14            1
38087  322289.0  Darwin's Journey                3.74       14            1

       max_players  rating_average  bgg_rank  owned_users  \
0                5            7.63       289       7213.0
1                5            7.63       289       7213.0
2                5            7.63       289       7213.0
3                5            7.63       289       7213.0
4                5            7.63       289       7213.0
...            ...             ...       ...          ...
38083            4            7.95      2993        277.0
38084            4            7.95      2993        277.0
38085            4            7.95      2993        277.0
38086            4            7.95      2993        277.0
38087            4            7.95      2993        277.0

                       mechanic_name     domain_name
0                       Dice Rolling  Strategy Games
1          Area Majority / Influence  Strategy Games
2                          Alliances  Strategy Games
3      Simultaneous Action Selection  Strategy Games
4                    Hand Management  Strategy Games
...                              ...             ...
38083         Turn Order: Stat-Based  Strategy Games
38084                      Contracts  Strategy Games
38085         Different Worker Types  Strategy Games
38086                 Set Collection  Strategy Games
38087        Point to Point Movement  Strategy Games

[38088 rows x 11 columns]' exported successfully to 'C:/Users/dfang/Downloads/datafiltered.csv'